env:
  global:
    PUBLISH_NPM_LATEST_FROM="master"
sudo: false
language: node_js
node_js:
  - "10.0.0"


script:
  - echo "running script"
  - cd app
deploy:
  - provider: script
    script: bash ./scripts/publish-edge.sh
    on:
      branch: develop 
  - provider: script
    script: pwd && ls && bash scripts/publish-tag.sh
    on:
      branch: travis
      # tags: true
